#!/bin/sh
# Lua environment manager 0.2
# Published under MIT license. Daniel Lima, 2016 <danielm@tinyhub.tk>

LUAS_CACHE="$HOME/.cache/luas"
LUAS_UPDATE="$LUAS_CACHE/update"
LUAS_VERSIONS="$LUAS_CACHE/versions"
LUAS_LUAROCKS="$LUAS_CACHE/luarocks_version"
MAKE="make -j$(nproc)"
mkdir -p "$LUAS_CACHE"
if [ -d ".luas" ]; then
	LUAS_DIR="$(pwd)/.luas"
else
	LUAS_DIR="$HOME/.luas"
fi
if [ ! -d "$LUAS_DIR" ]; then
	mkdir -p "$LUAS_DIR"
fi

help() {
	echo "luas 0.2	Lua environment manager"
	echo ""
	echo "Usage:"
	echo "  luas list			list versions"
	echo "  luas update			update version list"
	echo "  luas init <version>		create .luas in current dir and install <version>"
	echo "  luas install <version>	install lua <version> and latest luarocks"
	echo "  luas remove <version>	remove lua <version> and its luarocks tree"
	echo "  luas use <version>		setup environment to use <version>"
	echo "  luas help			print this message"
	echo ""
}

use() {
	luarocks="$LUAS_DIR/$1/bin/luarocks"
	if [ ! -x "$luarocks" ]; then
		echo "$1 is not installed." 1>&2
		exit 1
	fi
	if [ ! "$LUAS_PATH" ]; then
		export LUAS_PATH="$PATH"
	fi
	export PATH="$($luarocks path --lr-bin):$LUAS_PATH"
	export LUA_PATH="./?.lua;./?/init.lua;$($luarocks path --lr-path)"
	export LUA_CPATH="./?.so;$($luarocks path --lr-cpath)"
	exec "$SHELL"
}

list() {
	if [ ! -f "$LUAS_VERSIONS" ]; then
		echo "Could not connect to network, please try again later." 1>&2
		exit 1
	fi
	echo "Legend:"
	echo "   available"
	echo " - installed"
	echo " * active"
	echo ""
	echo "Versions:"
	cut -f1 "$LUAS_VERSIONS" | \
		while read -r ver; do
			if $(echo "$LUA_PATH" | fgrep -q "$ver"); then
				echo " * $ver"
			elif [ -d "$LUAS_DIR/$ver" ]; then
				echo " - $ver"
			else
				echo "   $ver"
			fi
		done
	echo ""
}

update() {
	echo "Updating package list... "
	if ! curl -# -o "$LUAS_UPDATE" "https://raw.githubusercontent.com/limadm/luas/master/update"; then
		echo "Could not connect to network, please try again later." 1>&2
		exit 1
	fi
	head -n-1 "$LUAS_UPDATE" >"$LUAS_VERSIONS"
	tail -n1  "$LUAS_UPDATE" >"$LUAS_LUAROCKS"
	echo "Done."
}

getpkg() {
	info="$(grep "$1" "$3")"
	url="$(echo "$info" | cut -f2)"
	md5="$(echo "$info" | cut -f3)"
	name="$(basename "$url" .tar.gz)"
	file="$LUAS_CACHE/$name.tar.gz"
	md5s="$(md5sum "$file" | cut -c1-32)"
	if [ "$md5" != "$md5s" ]; then
		if ! curl -# -L -o "$file" "$url"; then
			echo "Could not download package file, please try again later." 1>&2
			exit 1
		fi
	fi
	tar -xzf "$file" -C "$2"
	echo $name
}

platform() {
	# TODO support for more platforms
	p="$(uname | sed 's/./\l\0/g')"
	case "$p" in
	(darwin) echo macosx ;;
	(*)      echo $p     ;;
	esac
}

install() {
	if [ ! -f "$LUAS_VERSIONS" ]; then
		echo "An update is needed, please try again later." 1>&2
		exit 1
	fi

	echo "Installing $1..."
	install_dir="$LUAS_DIR/$1"
	mkdir -p "$install_dir"
	tmp_dir="$(mktemp -d)"

	lua_pkg="$(getpkg "$1" "$tmp_dir" "$LUAS_VERSIONS")"
	lua_dir="$tmp_dir/$lua_pkg"
	if echo "$1" | fgrep -q luajit; then
		$MAKE -C "$lua_dir" && $MAKE -C "$lua_dir" install PREFIX="$install_dir"
		ln -sf "$1" "$install_dir/bin/luajit"
	else
		sed -i "s;INSTALL_TOP= /usr/local;INSTALL_TOP= $install_dir;" "$lua_dir/Makefile"
		if !( $MAKE -C "$lua_dir" $(platform) && $MAKE -C "$lua_dir" install ); then
			echo "Could not build lua, please verify if build dependencies are installed in your system." 1>&2
			exit 1
		fi
	fi

	rocks_ver="$(cut -f1 "$LUAS_LUAROCKS")"
	rocks_pkg="$(getpkg "$rocks_ver" "$tmp_dir" "$LUAS_LUAROCKS")"
	rocks_dir="$tmp_dir/$rocks_pkg"
	export PATH="$install_dir/bin:$PATH"
	cd "$rocks_dir"
	if echo "$1" | fgrep -q luajit; then
		"$rocks_dir/configure" --lua-suffix=jit --with-lua-include="$install_dir/include/$(echo $1 | cut -c1-10)" --prefix="$install_dir"
	else
		"$rocks_dir/configure" --prefix="$install_dir"
	fi
	if !( $MAKE -C "$rocks_dir" build && $MAKE -C "$rocks_dir" install ); then
		echo "Could not build luarocks, please verify if build dependencies are installed in your system." 1>&2
		exit 1
	fi
	rm -rf "$tmp_dir"
	echo ""
	echo "Done."
}

remove() {
	install_dir="$LUAS_DIR/$1"
	if [ ! -d "$install_dir" ]; then
		echo "This version is not installed." 1>&2
		exit 1
	fi
	echo "Removing $install_dir..."
	rm -rf $install_dir
	export PATH="$LUAS_PATH"
	export LUA_PATH=
	export LUA_CPATH=
	echo "Done."
}

if [ ! -f "$LUAS_VERSIONS" ]; then
	update
fi

case "$1" in
(install)  install  $2 ;;
(remove)   remove   $2 ;;
(use)      use      $2 ;;
(update)   update      ;;
(list)     list        ;;
(*)        help        ;;
esac
